classes:
- system.linux.system.repo.ubuntu
- system.salt.master.pkg
- system.salt.minion.ca.salt_master
- system.salt.master.api
- system.reclass.storage.salt
- system.reclass.storage.system.ceph_monitor_cluster
- cluster.virtual-ceph-lab.ceph
- cluster.virtual-ceph-lab.infra
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: "https://github.com/LotharKAtt/ceph-virtual-lab.git"
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    linux_system_codename: xenial
    salt_api_password_hash: "$6$WV0P1shnoDh2gI/Z$22/Bcd7ffMv0jDlFpT63cAU4PiXHz9pjXwngToKwqAsgoeK4HNR3PiKaushjxp3JsQ8hNoJmAC6TxzVqfV8WH/"
    salt_master_host: ${_param:infra_config_deploy_address}
  reclass:
    storage:
      node:
        ceph_osd_node01:
          name: ${_param:ceph_osd_node01_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.ceph.osd
          params:
            salt_master_host: ${_param:infra_config_deploy_address}
            linux_system_codename: xenial
            single_address: ${_param:ceph_osd_node01_address}
        ceph_osd_node02:
          name: ${_param:ceph_osd_node02_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.ceph.osd
          params:
            salt_master_host: ${_param:infra_config_deploy_address}
            linux_system_codename: xenial
            single_address: ${_param:ceph_osd_node02_address}
        ceph_osd_node03:
          name: ${_param:ceph_osd_node03_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.ceph.osd
          params:
            salt_master_host: ${_param:infra_config_deploy_address}
            linux_system_codename: xenial
            single_address: ${_param:ceph_osd_node03_address}
        ceph_cfs_node01:
          name: ${_param:ceph_cfs_node01_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.ceph.cfs
          params:
            salt_master_host: ${_param:infra_config_deploy_address}
            linux_system_codename: xenial
            single_address: ${_param:ceph_cfs_node01_address}
        ceph_monitor_node01:
          params:
            linux_system_codename: xenial
            keepalived_vip_priority: 100
        ceph_monitor_node02:
          params:
            linux_system_codename: xenial
            keepalived_vip_priority: 101
        ceph_monitor_node03:
          params:
            linux_system_codename: xenial
            keepalived_vip_priority: 102

