classes:
- system.linux.system.single
- system.linux.system.repo.mcp.extra
- system.linux.system.repo.mcp.salt #FIXME
- system.linux.system.repo.saltstack.xenial
- system.linux.system.repo.ubuntu
- system.openssh.server.team.members.mlos
- system.openssh.server.team.tcpcloud
- cluster.virtual-ceph-lab.ceph
- cluster.overrides
parameters:
  _param:
    salt_version: 2017.7
    # infra service addresses
    infra_config_hostname: cfg01
#    infra_config_address: 172.16.10.100
#    infra_config_deploy_address: 192.168.10.100

    cluster_domain: virtual-ceph-lab.local
    cluster_name: virtual-ceph-lab
    apt_mk_version: nightly
    primary_interface: ens3
  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
      interface:
        primary_interface:
          enabled: true
          type: eth
          proto: dhcp
          #proto: static
          #name: ${_param:primary_interface}
          #address: ${_param:single_address}
          #netmask: 255.255.255.0
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
